# Generated by Django 2.1 on 2020-06-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='waiting',
            field=models.BooleanField(default=False),
        ),
    ]
