# Generated by Django 2.1 on 2020-06-29 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200629_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmation',
            name='waiting',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_confirmed',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
