# Generated by Django 3.0.7 on 2020-06-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0003_hospital_user'),
        ('Hospitals', '0003_auto_20200627_0517'),
    ]

    operations = [
    ]
