# Generated by Django 2.1 on 2020-06-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0002_auto_20200608_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_book',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='doctor_book',
            name='waiting_time',
        ),
        migrations.AddField(
            model_name='doctor',
            name='fees',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='waiting_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
