# Generated by Django 3.0.7 on 2020-06-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0004_copoun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='clinic_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=255),
        ),
    ]
